### ISSUE TITLE
Code Headings Have Back-ticks in "on this page" Accordion

### ISSUE THREAD

**Issue by bjcarlson42** [carlson-technologies/coffeeclass.io#60]
**Describe the bug**
Any heading that has inline code - i.e. `example`, is added to the headings accordion with the back-ticks. Because of this, when the user clicks, the user is not brought to the heading.

**To Reproduce**
1. Navigate to https://www.coffeeclass.io/articles/use-disclosure-menu-chakra-ui
2. Expand "on this page" accordion. This accordion is only found on medium and small screens so you may need to resize your browser.
3. Click "`onMouseEnter` and `onMouseLeave`"
4. Note that nothing happens

**Expected behavior**
I expect to be brought to that part of the page.

**Additional context**
- `get-headings` script: https://github.com/carlson-technologies/coffeeclass.io/blob/main/src/scripts/get-headings.ts
- Accordion component: https://github.com/carlson-technologies/coffeeclass.io/blob/main/src/components/HeadersAccordion.tsx

**Comment by Umayarz18** [comment]
![image](https://user-images.githubusercontent.com/61628982/154824349-9f0d339e-b012-4f50-aff8-de21d51c2cfd.png)
After looking at why this issue is happening, my guess is the get-headings script does not take into account back-ticks as it would be an object rather than a string like we would assume. 

I'm not familiar with regex yet but there might be something going on there in [`get-headings.ts`](https://github.com/carlson-technologies/coffeeclass.io/blob/main/src/scripts/get-headings.ts)
